---
title: "SNA_S21"
author: "Louis Göllner"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
# Setup-Chunk 
  # Daten einlesen
edges <- read.csv("https://raw.githubusercontent.com/gllnxr/Stuttgart21/main/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/gllnxr/Stuttgart21/main/nodes.csv", header=T, as.is=T, sep = ",")

# Ein Codebuch zu der Datenerhebung ist im folgenden Github-Verzeichnis zu finden.

https://github.com/gllnxr/Stuttgart21/blob/main/Codebuch.md

  # edgematrix erstellen
edgematrix <- as.matrix(edges)

  # igraph-Objekt erstellen
view_sna_proj <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed = F)

view_sna_proj
```

```{r Visualisierung}


  # Organisationen und Personen entsprechend kenntlich machen (two-mode-network); Zusatz: nach Parteien einfärben
V(view_sna_proj)[V(view_sna_proj)$party == "CDU"]$color <- "lightblue"
V(view_sna_proj)[V(view_sna_proj)$party == "FDP"]$color <- "yellow"
V(view_sna_proj)[V(view_sna_proj)$party == "GRUENE"]$color <- "darkgreen"
V(view_sna_proj)[V(view_sna_proj)$party == "SPD"]$color <- "darkred"
V(view_sna_proj)[V(view_sna_proj)$party == "SÖS"]$color <- "grey25"


V(view_sna_proj)[V(view_sna_proj)$type == 1]$shape <- "circle"

V(view_sna_proj)[V(view_sna_proj)$type == 2]$shape <- "square" 
  
  # nachfolgender Befehl errechnet den degreewert aller nodes in einen neuen datensatz "degree_option", dadurch kann man im plot Befehl dann die Größe der Nodes abhängig von ihrem degreewert machen!
degree_option <- degree(view_sna_proj, mode="all")

plot(view_sna_proj,
     set.seed=12,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size = degree_option*0.25,
     vertex.label.cex=0.5,
     main = "Netzwerk der beteiligten Personen und Organisationen und deren Beziehungen zum Bauprojekt Stuttgart 21",
     sub = "Die Größe der Knoten ist abhängig von ihren jeweiligen Degreewerten — Datenerhebung erfolgte durch Louis G, Sinan K, Mia M, David V, Paul A")
```

```{r Erste Untersuchungen}

count_components(view_sna_proj)
  # Das Netzwerk SNA_S21 hat genau eine Komponente.

edge_density(view_sna_proj)
  # Das Netzwerk SNA_S21 hat eine Kantendichte von etwa 3,09%

cl_sna <- cluster_walktrap(view_sna_proj)

  # Cluster-Analyse der einzelnen Cluster des Netzwerks SNA_S21 (Cluster-Walktrap-Analyse)
plot(cl_sna,
     view_sna_proj,
     main = "Cluster-Walktrap Analyse des Netzwerks SNA_S21",
     set.seed=12,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size = 2,
     vertex.label.cex=0.5)

  # Degree-Berechnungen aller Edges eines Nodes (?)
sna_deg <- degree(view_sna_proj, mode = "total")
which.max(sna_deg)
  # Logischerweise hat das DBPSU den höchsten Degree-Wert. Alle sind (über verschiedene Beziehungen) mit dem Projekt verbunden.

  # Betweenness-Berechnungen
sna_betw <- betweenness(view_sna_proj, directed = F, normalized = T)
which.max(betweenness(view_sna_proj))
  # Auch hier ist das DBPSU der Node mit dem höchsten Betweenness-Wert.

  # Closeness-Berechnung
sna_close <- closeness(view_sna_proj)
which.max(closeness(view_sna_proj))
  # Auch hier ist natürlich das DBPSU der Node mit dem höchsten Closeness-Wert.

  # Eigenvector-Zentralitäts-Berechnung
sna_eigenvec <- eigen_centrality(view_sna_proj)
sna_eigenvec_new <- sna_eigenvec$vector
which.max(sna_eigenvec_new)
  # Auch hier ist das DBPSU der Node mit dem höchsten Eigenvector-Zentralitäts-Wert.

  # Erstellung eines Dyaden-Zensus.
dyad_census(view_sna_proj)
  # Es gibt 172 mutual Verbindungen im Netzwerk SNA_S21 -> ungerichtet, daher zudem die Anzahl an Edges

  # Reziprozitäts-Berechnung
reciprocity(view_sna_proj, mode = "ratio")
  # Da es sich beim Netzwerk SNA_S21 um ein ungerichtetes Netzwerk handelt kann die Reziprozität nicht verlässlich festgestellt werden. Sie beträgt hier genau 1.
```
